# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c586feaaef2646cc2899b9930e13a9844ff8f698478caf1fbae03d68d3ac25f5c64442e7d0ab5b6f36cfcec1c1aa7e07bcc0a46e4b9e67110d0ba4ed2e8e15

test:
  secret_key_base: 059816cc30e646d35a811bf6b26f8c1d7f914d0b6eb9f60196bea10bd994ecad739f5ca8b93603751c88500c9cd6e1a9e1704ca900eb92ad2710d92c57a9f9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
